# Generated by Django 3.0.3 on 2020-03-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20200306_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type_post',
            field=models.CharField(choices=[('S', 'sell'), ('B', 'buy')], default='', max_length=2),
        ),
    ]
