# Generated by Django 3.0.3 on 2020-03-07 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0003_book_type_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='type_post',
            field=models.CharField(choices=[('S', 'Sell'), ('B', 'Buy')], max_length=1),
        ),
    ]
