# Generated by Django 3.0.3 on 2020-03-08 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20200308_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
