# Generated by Django 3.0.3 on 2020-03-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
